[package]
name = "catcache"
version = "0.1.0"
authors = ["Michael Mokrysz <hi@46b.it>"]

[dependencies]
ansi_term = "*"
rustc-serialize = "*"
hyper = "0.9.10"
regex = "0.1"
chan = "0.1"
iron = "0.4.0"
router = "0.2.0"
